### ISSUE TITLE
DBSecret Resource is Missing NoEcho Setting to Avoid Leaking password to logs

### ISSUE THREAD

**Issue by sprkyco** [aws-samples/amazon-sagemaker-optuna-hpo-blog#15]
It's a security best practice to set `NoEcho:True` for any randomly generated credentials as part of cloudformation template.

**Comment by hariby** [comment]
You are true, the pull request #16 is merged.

**Comment by hariby** [comment]
CloudFormation doesn't echo the secret created SecretsManager. `NoEcho` is used when you specify passwords in the CloudFormation `Parameters` (which is not applicable to our case).
